name: Format

on:
  pull_request:

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up .NET
        uses: actions/setup-dotnet@v4

      - name: Format whitespace
        run: dotnet format whitespace . --folder --verify-no-changes
