name: Publish

on:
  workflow_dispatch:
    inputs:
      feed:
        description: NuGet feed
        required: true
        default: Staging
        type: choice
        options:
          - Production
          - Staging
      version:
        description: Library version
        required: true
        default: 1.5.1
        type: string

jobs:
  publish:
    name: Test and publish
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIG: Release
      WORKING_DIR: .
    steps:

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up .NET
        uses: actions/setup-dotnet@v3

      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: dotnet restore

      - name: Build
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          dotnet build -c ${{ env.BUILD_CONFIG }} --no-restore \
            -p:Commit=${{ github.sha }} \
            -p:VersionPrefix=${{ github.event.inputs.version }}

      - name: Test
        working-directory: ${{ env.WORKING_DIR }}
        env:
          TEST_OPTS: -c ${{ env.BUILD_CONFIG }} --no-build
        run: |
          dotnet test .

      - name: Publish
        working-directory: ${{ env.WORKING_DIR }}
        env:
          PACK_OPTS: -c ${{ env.BUILD_CONFIG }} --no-build -p:VersionPrefix=${{ github.event.inputs.version }}
        run: |
          dotnet pack . ${{ env.PACK_OPTS }}
          
          dotnet nuget push **/*.nupkg \
            -k ${{ github.event.inputs.feed == 'Production' && secrets.NUGET_API_KEY || secrets.NUGETTEST_API_KEY }} \
            -s ${{ github.event.inputs.feed == 'Production' && 'https://api.nuget.org/v3/index.json' || 'https://apiint.nugettest.org/v3/index.json' }}
