name: Publish

on:
  workflow_dispatch:
    inputs:
      feed:
        description: NuGet feed
        required: true
        default: Staging
        type: choice
        options:
          - Production
          - Staging
      version:
        description: Library version
        required: true
        default: 1.5.2
        type: string

jobs:
  publish:
    name: Test and publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      BUILD_CONFIG: Release
      NUGET_HOST: ${{ inputs.feed == 'Staging' && 'https://int.nugettest.org' || 'https://www.nuget.org' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set up .NET
        uses: actions/setup-dotnet@v6

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: |
          dotnet build -c ${{ env.BUILD_CONFIG }} --no-restore \
            -p:Commit=${{ github.sha }} \
            -p:Version=${{ github.event.inputs.version }}

      - name: Test
        run: dotnet test . -c ${{ env.BUILD_CONFIG }} --no-build

      - name: NuGet login
        uses: nuget/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
          audience: ${{ env.NUGET_HOST }}
          token-service-url: ${{ env.NUGET_HOST }}/api/v2/token

      - name: Publish
        run: |
          dotnet pack . -c ${{ env.BUILD_CONFIG }} --no-build -p:Version=${{ github.event.inputs.version }}
          dotnet nuget push **/*.nupkg \
            -k "${{ steps.login.outputs.NUGET_API_KEY }}" -s ${{ env.NUGET_HOST }}/api/v2/package
